### ISSUE TITLE
Divison by zero in Mapper::map

### ISSUE THREAD

**Issue by chr-hertel** [Xosofox/codesound#2]
i ran into an error while moving your example_dir to a composer plugin. any clue about that?

<img width="1147" alt="bildschirmfoto 2017-10-31 um 00 58 38" src="https://user-images.githubusercontent.com/2852185/32201333-ba893b44-bdd6-11e7-878e-f0f58538baa6.png">

**Comment by xosofox** [comment]
The mapper is not stable yet; algorithm for maping the input data needs some more tests and definitely more error handling...

**Comment by xosofox** [comment]
Some changes and improvements in Mapper/Converter.

**Comment by xosofox** [comment]
Isses should be fixed. Please re-open if it returns
